# Konfiguracia pre preferovane porty
PREFFERED_PORT = "COM14"
LAST_CONNECTED_PORT = "COM14"

# Nastavenia kamery
CAMERA_DIMENSIONS = (640, 480)
MAXIMUM_STORED_DEPTH_DISTANCES = 10 
RGB_CAMERA_FPS = 30
DEPTH_CAMERA_FPS = 15
DEPTH_CAMERA_KERNEL_SIZE = 5

# Globalne nastavenia
MM_TO_PIXEL = 3.7795275591
DIFFERENCE_EYES = (-43, 43) # (Left, Right) in mm
DIFFERENCE_HEAD = (0, -215, 65) # (dx, dy, dz) in mm
EYE_LIMIT_HORIZONTAL = 30
EYE_LIMIT_VERTICAL = 40
EYE_LIMIT_LID = 50
